[package]
name = "rIC3"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aig = { path = "../aig-rs" }
minisat = { path = "../minisat-rs" }
cadical = { path = "../cadical-rs" }
kissat = { path = "../kissat-rs" }
logic-form = { path = "../logic-form" }
clap = { version = "4.5.11", features = ["derive"] }
rand = "0.8.5"
ctrlc = { version = "3.4.1", features = ["termination"] }
giputils = { path = "../giputils" }
satif = { path = "../satif" }
bitfield-struct = "0.8.0"
abc = { path = "../abc-rs" }
tempfile = "3.10.1"
process_control = "4.1.0"
nix = { version = "0.27.1", features = ["signal"] }
procspawn = "1.0.0"
btor = { path = "../btor-rs" }

[features]
default = ["no_bound_check"]
no_bound_check = ["logic-form/no_bound_check", "giputils/no_bound_check"]
