[package]
name = "ic3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aig = { path = "../aig-rs" }
minisat = { path = "../minisat-rs" }
logic-form = { path = "../logic-form" }
clap = { version = "4.3.0" , features = ["derive"] }
rand = "0.8.5"
cudd = { path = "../cudd-rs" }
serde_json = "1.0.107"

[profile.release]
debug = true
