[package]
name = "rIC3"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aig = { path = "../aig-rs" }
minisat = { path = "../minisat-rs" }
cadical = { path = "../cadical-rs" }
kissat = { path = "../kissat-rs" }
logic-form = { path = "../logic-form" }
clap = { version = "4.3.0", features = ["derive"] }
rand = "0.8.5"
ctrlc = { version = "3.4.1", features = ["termination"] }
giputils = { path = "../giputils" }
satif = { path = "../satif" }
transys = { path = "../transys" }
bitfield-struct = "0.5.6"
sbva = { path = "../sbva-rs" }
abc = { path = "../abc-rs" }
tempfile = "3.10.1"

[features]
default = ["no_bound_check"]
no_bound_check = [
    "logic-form/no_bound_check",
    "giputils/no_bound_check",
    "transys/no_bound_check",
]
