[package]
name = "ic3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aig = { path = "../aig-rs" }
sat-solver = { path = "../sat-solver" }
logic-form = { path = "../logic-form" }
clap = { version = "4.3.0" , features = ["derive"] }
pic3 = { path = "../pic3/pic3" }

[profile.release]
debug = true