[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-stdlib=libc++"]

[target.x86_64-unknown-linux-musl]
linker = "/usr/local/musl/bin/x86_64-unknown-linux-musl-g++"
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=-static"
]

[env]
CC_x86_64_unknown_linux_musl = "/usr/local/musl/bin/x86_64-unknown-linux-musl-gcc"
CXX_x86_64_unknown_linux_musl = "/usr/local/musl/bin/x86_64-unknown-linux-musl-g++"
AR_x86_64_unknown_linux_musl = "/usr/local/musl/bin/x86_64-unknown-linux-musl-ar"