name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: jwlawson/actions-setup-cmake@v2.0.2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Initialize and update submodules
      run: git submodule update --init --recursive
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
